server:
  port: 8081

spring:
  application:
    name: til-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: secret
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
