server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  config:
    # yml registration
    import: application-secret.yml

  # h2 database
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console




  # jpa database
  jpa:
    hibernate:
      ddl-auto: create
    format-sql: true


logging:
  level:
    propofol:
      userservice: debug